### ISSUE TITLE
actionButtonStyle

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#11]
When theming the button everything work as expected for the desktop view, here is an example:

![image](https://user-images.githubusercontent.com/39314023/141133103-16ba24f4-acf4-42cf-9b52-f5dcf7492ee3.png)

But when going into the mobile view the theming of the button is not right.  I would expect the button to be orange in my example, like the image shown previously
![image](https://user-images.githubusercontent.com/39314023/141133367-1c652f79-914d-4271-aac7-2305bb26c984.png)

When looking at the code, you would need to change the getter
`Widget get _formPart => FormPart(`

for a function to pass the right actionButtonStyle depending of the View.
```
Widget _formPart(ButtonStyle? style) => ...
...
actionButtonStyle: style,
...
)
```
By doing, this everything working like a charm.

Also, the actionTextStyle supersede the ButonStyle texttheme. (this is not obvious at first sight)
An idea would be removing the  actionTextStyle property completly and only use the actionButtonStyle.

Sounds ok for you?

**Comment by bahricanyesil** [comment]
Ah, sorry that was my mistake. I couldn't understand the issue at first. Now, it's clear. You're right. We should have distinct button styles for action/change action buttons for each view (mobile/desktop). There may also be some other custom fields that should depend on the view. I will fix this issue this weekend by also looking for some other possible fields like this one.

Thanks for your support, effort, and detailed explanations.
