### ISSUE TITLE
Button Style for change language

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#12]
Styling the language button is different than styling the login button. If there is no particular reason, I would like to style it like the other button using a ButtonStyle.

**Comment by wer-mathurin** [comment]
My bad, I've not see the property (changeLangButtonStyle) so maybe we can remove the other properties?

**Comment by bahricanyesil** [comment]
I just thought to give option users to change some specific properties (e.g. border-color) without having to write all button style-related things from scratch. However, now I couldn't understand why I didn't implement it by using the functionality of the "merge" function just as I did for some button styles and text styles. Thanks for pointing out, those separated fields are unnecessary, will be removed.

**Comment by bahricanyesil** [comment]
> I just thought to give option users to change some specific properties (e.g. border-color) without having to write all button style-related things from scratch. However, now I couldn't understand why I didn't implement it by using the functionality of the "merge" function just as I did for some button styles and text styles. Thanks for pointing out, those separated fields are unnecessary, will be removed.

Haha, now I realized that I have already implemented it by using merge but additionally created those extra fields too, interesting.
