### ISSUE TITLE
Add a way to style the default language dialog

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#14]
We are not able change the look and feel of the dialog box.

If you can add a property(LanguageTheme ) to the AnimatedLogin class like proposed bellow

Classes skeleton to show you what I think cover styling of the current available dialog
```
class LanguageTheme {
  final ButtonStyle? languageButtonStyle;
  final AnimatedDialogTheme? dialogtheme;
}

class AnimatedDialogTheme {
  final TextStyle? title;
  final TextStyle? items;
  final DividerTheme? dividerTheme;
  final ShapeBorder? shape;
}
```

**Comment by bahricanyesil** [comment]
I actually created `changeLangOnPressed` field for this purpose. However, for those just want to make small ui changes by preserving the current single choose dialog logic, those theme classes would be beneficial. I will be working on them weekend.
