### ISSUE TITLE
DISCUSSION: Section customization and simplification

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#27]
One use case is being able to hide the Welcome title or do more fancy stuff.

What do you think of being able to pass Widget instead of text for LoginText where it make sense and/or completely removing LoginText, I will show you later with example what I have in mind.

By default, if no widget it provided use a Text widget with default TextTheme. (exactly like today)
This can also remove the need of passing the TextTheme to the loginTheme.

If you need you style the Welcome here is what I have in mind...

If you need to change the Style
```
LoginTheme(
   welcome: (defaultText, languageOption) => Text(defaultText, style: TextStyle(...))
);
```

If you need to remove the widget and space.
```
LoginTheme(
   welcome: (defaultText, languageOption) => Container()
);
```

By providing the languageOption is simpler to display the appropriate message
```
LoginTheme(
   welcome: (defaultText, languageOption) => Text(MY_LOCALIZED_MESSAGE(languageOption))
);
```

For customizing the TextFormField maybe we can use the standard InputDecoration instead of passing the text in LoginText and style in LoginTheme.

```
LoginTheme(
   login: (decoration, languageOption) => decoration.copyWith(...)
);
```

I think this will remove the need for multiple properties like welcomePadding.  Since you can change the padding by providing yours :-)

**Comment by bahricanyesil** [comment]
Thanks for your idea @wer-mathurin ! Can you just open a discussion [here](https://github.com/bahricanyesil/flutter-animated-login/discussions/categories/ideas) instead of an issue? After you created the discussion, we talk about it them and if we finalize our conversation, we can create an issue.

Please attached the link to the discussion hereafter you created it so that I can close this issue.

Thanks a lot!

**Comment by wer-mathurin** [comment]
Done
https://github.com/bahricanyesil/flutter-animated-login/discussions/30

Louis-Michel Mathurin


T : (514) 705-0228
