### ISSUE TITLE
Changing the width of the login button with the style does not work

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#28]
I tried all those properties without any effect on the login button size.

fixedSize: MaterialStateProperty.all(Size.fromWidth(220)),
minimumSize: MaterialStateProperty.all(Size.fromWidth(220)),
maximumSize: MaterialStateProperty.all(Size.fromWidth(220)),

**Comment by bahricanyesil** [comment]
I will try to detect the reason as soon as possible, thanks for reporting.

**Comment by bahricanyesil** [comment]
Hi @wer-mathurin , I couldn't reproduce this. Are you sure to set these properties on `loginDesktopTheme` if you are using the app on a large-sized (pc) device and `loginMobileTheme` if you are using it on a small-sized (mobile phone) device?

I'm attaching the working code and the screenshot of the output:

```
AnimatedLogin(
      loginDesktopTheme: _desktopTheme,
      loginMobileTheme: _mobileTheme,
    );
    
  LoginViewTheme get _desktopTheme => _mobileTheme.copyWith(
        actionButtonStyle: _mobileTheme.actionButtonStyle?.copyWith(
          foregroundColor: MaterialStateProperty.all(Colors.white),
        ),
      );

  LoginViewTheme get _mobileTheme => LoginViewTheme(
        actionButtonStyle: ButtonStyle(
          fixedSize: MaterialStateProperty.all(Size.fromWidth(100)),
        ),
      );
```

**Screenshots:**
<img src="https://user-images.githubusercontent.com/60237280/143298935-8485bf52-f1cd-40b6-83b8-86aeb6d476dd.png" width="40%">
<img src="https://user-images.githubusercontent.com/60237280/143298943-19150465-c067-4730-9341-1d57ac15b128.png" width="60%">

**Comment by wer-mathurin** [comment]
on the mobile, I didn't test it on desktop.

  loginMobileTheme: _loginTheme.copyWith(
          actionButtonStyle: ButtonStyle(
            backgroundColor: MaterialStateProperty.all(kBlueLight),
            side: MaterialStateProperty.all(BorderSide.none),
            foregroundColor: MaterialStateProperty.all(Colors.white),
            textStyle: MaterialStateProperty.all(TextStyle(fontSize: 18)),
            fixedSize: MaterialStateProperty.all(Size.fromWidth(220)),
            minimumSize: MaterialStateProperty.all(Size.fromWidth(220)),
            maximumSize: MaterialStateProperty.all(Size.fromWidth(220)),
          ),

try to make the button larger.

**Comment by bahricanyesil** [comment]
Can you try this code sample? I got the result in the screenshots.

```
LoginViewTheme get _desktopTheme => _mobileTheme.copyWith(
        actionButtonStyle: ButtonStyle(
          foregroundColor: MaterialStateProperty.all(Colors.white),
          fixedSize: MaterialStateProperty.all(Size.fromWidth(420)),
        ),
      );

  LoginViewTheme get _mobileTheme => LoginViewTheme(
        backgroundColor: Colors.blue, // const Color(0xFF6666FF),
        formFieldBackgroundColor: Colors.white,
        formWidthRatio: 60,
        actionButtonStyle: ButtonStyle(
          foregroundColor: MaterialStateProperty.all(Colors.white),
          fixedSize: MaterialStateProperty.all(Size.fromWidth(420)),
        ),
      );
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/60237280/143307105-2c6a40f3-f4a3-4837-b469-2ec4ece4305a.png)
![image](https://user-images.githubusercontent.com/60237280/143307131-20a9cf9e-92a1-4614-ba97-42d6975e5d5d.png)

**Comment by wer-mathurin** [comment]
I'll try it later today.

**Comment by bahricanyesil** [comment]
Thanks a lot, @wer-mathurin . Just inform me after you tried. If we can solve the issue, I will publish version 1.0.0 🥳

**Comment by VB10** [comment]
We're waiting for a new version @bahricanyesil 🥰

**Comment by wer-mathurin** [comment]
@bahricanyesil : The problem was cause by using minimumSize and maximumSize.  This do not expand the sized of the widget base, and just decrease the font size to fit it in the button.

But fixedSize with alone do the job ! In fact if you mixed it with other properties this case a BoxConstraint exception!  
I was not looking to have a fix size but that's fair.  If we can override the button widget like we discussed in other tickets!  I will be able to have a button with a fix font size and button expanding !

So we can close this issue.

**Comment by bahricanyesil** [comment]
@wer-mathurin , this is what I tried and what result I encountered. I manipulated the font size extremely big for empirical aim and used `minimumSize`,  `maximumSize`, and `fixedSize.` together. Still, I can change the size with the help of `fixedSize`. You can try the code below and try to figure out what's going wrong in your case.
Note: The only thing that will not work is if you set the height or width of the button so small that the text cannot fit (e.g. height is 10 and font size is 100). Since if we allow this it will cause overflow, I eliminated these unwanted results.

**Code:**

```
LoginViewTheme get _desktopTheme => _mobileTheme.copyWith(
        actionButtonStyle: ButtonStyle(
          foregroundColor: MaterialStateProperty.all(Colors.white),
          maximumSize: MaterialStateProperty.all(Size(1000, 300)),
          minimumSize: MaterialStateProperty.all(Size(300, 100)),
          fixedSize: MaterialStateProperty.all(Size(800, 100)),
          textStyle: MaterialStateProperty.all(TextStyle(fontSize: 100)),
        ),
      );

  LoginViewTheme get _mobileTheme => LoginViewTheme(
        actionButtonStyle: ButtonStyle(
          foregroundColor: MaterialStateProperty.all(Colors.blue),
          maximumSize: MaterialStateProperty.all(Size(1000, 300)),
          minimumSize: MaterialStateProperty.all(Size(300, 100)),
          fixedSize: MaterialStateProperty.all(Size(400, 100)),
          textStyle: MaterialStateProperty.all(TextStyle(fontSize: 100)),
        ),
      );
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/60237280/143395112-ef47b85c-8ef9-4b5a-8b5a-04f8b547f989.png)
![image](https://user-images.githubusercontent.com/60237280/143395442-60213c2d-b7f9-48bd-9929-9426934c675c.png)

**Comment by bahricanyesil** [comment]
> @bahricanyesil : The problem was cause by using minimumSize and maximumSize. This do not expand the sized of the widget base, and just decrease the font size to fit it in the button.
> 
> But fixedSize with alone do the job ! In fact if you mixed it with other properties this case a BoxConstraint exception! I was not looking to have a fix size but that's fair. If we can override the button widget like we discussed in other tickets! I will be able to have a button with a fix font size and button expanding !
> 
> So we can close this issue.

For the discussion, I will try to look at it in my first free time with a fresh mind. Thanks.
