### ISSUE TITLE
Taping on login does not remove focus from TextFields

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#36]
**Describe the bug**
After entering a password or username and taping login on mobile.  The TextField continue to have focus.  So the keyboard is still showing.

Expected
When tapin or clicking on login, the cursor is remove from the textfield.  So this is cleaner and when showing a snackbar for showing error while login this is not hide behind the keyboard (on android at least! )

**Comment by wer-mathurin** [comment]
@bahricanyesil Pull-Request done and fixing the problem, also correct a missing disposal of the passwordConfirm FocusNode

**Comment by bahricanyesil** [comment]
I'm testing and reviewing it. Thanks, @wer-mathurin !

**Comment by wer-mathurin** [comment]
I was observing it in the Android Emulator

Quite frankly I'm not able to reproduce it either on my side with a minimalist example!  But in our app, this is happening :-(
This is probably related to the use of another plugging !!!

But applying the "fix" in the PR does the tricks :-)

https://user-images.githubusercontent.com/39314023/143473761-cdb1e70b-67d2-4875-a1e8-ee4225b9e7c8.mp4

.

**Comment by bahricanyesil** [comment]
That's really strange but it sounds that it is related to your own implementation more than the package itself. I now tried to validate with the help of dialogs instead of the default text form field validation and it perfectly removed the focus. It will be better to take any action after detecting the real reason for the error. Instead of specifically removing the focus from some predefined focus nodes, it will be better to use `FocusScope.of(context).unfocus();` to not have a problem in any other case.

**Comment by wer-mathurin** [comment]
I investigate a little bit, and I found out the problem is trigger by calling a Bloc from the onLogin.  But my bloc only doing basic stuff, and change the state for an error, if something happen.  so I can show the error.

But when I investigated, I found that the _Form is being rebuild lot, lot of times when only focusing on a textfield.  And even more when clicking on the login button after focussing on textfield.  I'm not sure if this can cause a side effect.  And because you use getter(a function) to get the Form, I think this mean you are sending back a new instance of that Form.

But still, I can't wrap my mind why I have this effect in my app.  I'm wondering if this is not a concurrent issues...

**Comment by bahricanyesil** [comment]
Are you sure to rebuild lots of times? I now tried with the example app I provided and the form part is reloaded multiple times only in the animation effect. Other than that, for the input focus and other things, it is not rebuilt. Even if I use setState after the resulting dialog on login operation, the animated widget is rebuilt only one time.

What insight I achieved from your explanation is that the problem is related to your state-management method. Can you check your code and also try to detect how many times the method calls the animated login widget is called (I mean the build method in your widget, LoginScreen in the example project). Also if you are using some extra methods, you can check how many times they are executed.

**Comment by wer-mathurin** [comment]
Add this line at the first line of the build method
`print('build called');`

in _FormPart class


run this code

```
void main() {
  runApp(
    MaterialApp(
      home: AnimatedLogin(
        loginMobileTheme: LoginViewTheme(
          textFormStyle: TextStyle(color: Colors.white),
        ),
        passwordValidator: ValidatorModel(length: 0),
        onLogin: (loginData) async {},
      ),
    ),
  );
}
```

_You will have (call twice on startup)_
**2** I/flutter ( 4918): build called

_Now select the email textfield you will have:_
2 I/AssistStructure( 4918): Flattened final assist data: 420 bytes, containing 1 windows, 3 views
E/SpannableStringBuilder( 4918): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
**I/flutter ( 4918): build called**
I/chatty  ( 4918): uid=10157(com.example) 1.ui identical 5 lines
**I/flutter ( 4918): build called**

Now enter a password and click on the login button:
**2 I/flutter ( 4918): build called** (call twice here)
I/chatty  ( 4918): uid=10157(com.example.teamflow) 1.ui identical 5 lines
**I/flutter ( 4918): build called**

This is related to the visibility of the keyboard.


As you can see this is not related to any state library.  Just pure AnimatedLogin beavior.

**Comment by wer-mathurin** [comment]
Add this line at the first line of the build method
`print('build called');`

in _FormPart class


run this code

```
void main() {
  runApp(
    MaterialApp(
      home: AnimatedLogin(
        loginMobileTheme: LoginViewTheme(
          textFormStyle: TextStyle(color: Colors.white),
        ),
        passwordValidator: ValidatorModel(length: 0),
        onLogin: (loginData) async {},
      ),
    ),
  );
}
```

_You will have (call twice on startup)_
**2** I/flutter ( 4918): build called

_Now select the email textfield you will have:_
2 I/AssistStructure( 4918): Flattened final assist data: 420 bytes, containing 1 windows, 3 views
E/SpannableStringBuilder( 4918): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
**I/flutter ( 4918): build called**
I/chatty  ( 4918): uid=10157(com.example) 1.ui identical 5 lines
**I/flutter ( 4918): build called**

Now enter a password and click on the login button:
**2 I/flutter ( 4918): build called** (call twice here)
I/chatty  ( 4918): uid=10157(com.example.teamflow) 1.ui identical 5 lines
**I/flutter ( 4918): build called**

This is related to the visibility of the keyboard.


As you can see this is not related to any state library.  Just pure AnimatedLogin beavior.

**Comment by bahricanyesil** [comment]
Oh, I got it now. It's a mobile-related issue, not reproducible on the web. BTW, I didn't mention the state library but your implementation.

Now, I'm looking at this issue.

**Comment by bahricanyesil** [comment]
@wer-mathurin  can you just try the branch that I opened a pull request. If it fixes the problem, I will merge.

**Comment by wer-mathurin** [comment]
I will try it tomorrow!

**Comment by bahricanyesil** [comment]
I also have to merge it tomorrow even if it works. Good night for me!

Healthy days ✨

**Comment by wer-mathurin** [comment]
@bahricanyesil : Finally I had 5 minutes to test it and it solved the re-build **AND** the weird behavior that I  had!  So my guest was probably right :-)

**Comment by bahricanyesil** [comment]
Hi again @wer-mathurin , I tried to remove media query dependency to avoid multiple rebuilds on window size changes and also prevent the double build at the beginning. Can you check the last version of the branch just to be sure everything still works like a charm?

**Comment by wer-mathurin** [comment]
@bahricanyesil this is working.

You need to also look at the animation triggering more than 26 builds on the mobile.(when clicking on signup)  This is not suppose to happen.

Here is an example that show that the MovingWidget **is not rebuild when moving**.

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: MyWidget(),
    ),
  );
}

class MyWidget extends StatefulWidget {
  MyWidget({Key? key}) : super(key: key);

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget>
    with SingleTickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(
    duration: const Duration(seconds: 2),
    vsync: this,
  );

  late final Animation<Offset> _offsetAnimation = Tween<Offset>(
    begin: Offset.zero,
    end: const Offset(1.5, 0.0),
  ).animate(CurvedAnimation(
    parent: _controller,
    curve: Curves.elasticIn,
  ));

  @override
  Widget build(BuildContext context) {
    print('build called');
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        SlideTransition(
          position: _offsetAnimation,
          child: MovingWidget(),
        ),
        SizedBox(height: 50),
        ElevatedButton(
            onPressed: () {
              if (_controller.isCompleted) {
                _controller.reverse();
              } else {
                _controller.forward();
              }
            },
            child: Text('Sing in'))
      ],
    );
  }
}

class MovingWidget extends StatelessWidget {
  const MovingWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    print('MovingWidget build');
    return Container(
      child: Icon(Icons.home),
      color: Colors.red,
      height: 100,
      width: 100,
    );
  }
}
```

**Comment by bahricanyesil** [comment]
That's because `AnimatedBuilder` I guess, if you use it most probably the same thing will happen to you also. I don't remember the exact reason why I used AnimatedBuilder in this scenario at the initial implementation but I will look at it.

**Comment by wer-mathurin** [comment]
This is just the way you are using it.

In the builder method you are providing widget, so each time this is rebuild.

```
AnimatedBuilder(
      animation: animationController,
      builder: (_, __) => isLandscape ? _webView : _mobileView,
    );
```


But if you pass a chid to the AnimatedBuilder like bellow, this will not trigger the rebuild

```
AnimatedBuilder(
          child: MovingWidget(),
          animation: _offsetAnimation,
          builder: (context, child) => Transform.translate(
            offset: _offsetAnimation.value,
            child: child,
          ),
        ),
```

**Comment by bahricanyesil** [comment]
Yes, that will be [great optimization](https://api.flutter.dev/flutter/widgets/AnimatedBuilder-class.html) and must to do but it will not be easy like that in my case I guess. There are different animations, so I should firstly separate them and behave differently. I will not be available for almost 10 days since the next week will be an intensive week for me with lots of work. If you can and want to implement/change the logic according to this optimization, I can review, test, and merge.

**Comment by bahricanyesil** [comment]
Hi, after a long time!

I changed the use of animated builder and optimized the general management, avoided unnecessary rebuilds.

Feel free to reopen an issue about this topic if you encounter any problems.
