### ISSUE TITLE
Add a tutorial for how to implement FIREBASE

### ISSUE THREAD

**Issue by fisforfaheem** [bahricanyesil/flutter-animated-login#40]
add firebase logi nand signup

**Comment by bahricanyesil** [comment]
Thanks for pointing it out. Although firebase authentication is a customized version of the general flow, I will try to look at what can be done in the upcoming weeks, stay tuned.

(Unfortunately, I have my final exams these days so cannot focus on the package.)

**Comment by fisforfaheem** [comment]
No problem, Brother I will remind you :) 

Really adding this (options) will help beginers have easy curves of learning

**Comment by AlimFreight** [comment]
> No problem, Brother I will remind you :)
> 
> Really adding this (options) will help beginers have easy curves of learning

I would say firebase or another real world backend solution for instance very popular nowadays firebase alternative AppWrite https://appwrite.io/ it's open source as well.

**Comment by fisforfaheem** [comment]
but most companies want you to have skills.... i can use flutter fire UI
but it wont work with flutter web at all


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
01/28/22,
10:52:48 PM

**Comment by bahricanyesil** [comment]
> but most companies want you to have skills.... i can use flutter fire UI but it wont work with flutter web at all [image: Mailtrack] <https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&> Sender notified by Mailtrack <https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&> 01/28/22, 10:52:48 PM
> […](#)

Adding this helper-optional to use functions can be a great idea. However, I have just used Firebase's phone verification system and did authentication-related things mostly with other back-end solutions, in-company back-end projects, and so on.

Since this request is "more customized" than the other changes that the package requires at this time and it should also be built on a well-based architecture for connection, I just marked it as "long-term future". Adding those functionalities with some custom parameters is an easy thing. However, if we strongly decide to add this functionality, we should also create a strong architecture for the firebase connection to maintain the quality of the package.

If anyone is volunteering to implement this in a shorter time, I can review and merge it.

Thanks.

**Comment by fisforfaheem** [comment]
is used the following code to make login work....however, I don't have the skills to add signup and recover password.... :)

Future<String?> _signIn(LoginData data) async {
    try {
      var d = await FirebaseAuthWeb.instance
          .signInWithEmailAndPassword(data.name, data.password);
      print(d.user);
      if (d.user!.displayName != '') {
        isFound = true;
        // setState(() {});

      }
      return null;
    } catch (e) {
      print(e);
      // return 'User not exists';
      // Get.snackbar("Info", "Invalid");
    }
  }

**Comment by fisforfaheem** [comment]
![image](https://user-images.githubusercontent.com/35878088/155281972-c7dfcab6-75a1-460d-bc81-a937754b1cea.png)

**Comment by fisforfaheem** [comment]
but i used this package instead :   flutter_login: ^3.1.0
 because it was working

**Comment by bahricanyesil** [comment]
I am not planning to add this example currently because it is not directly related to the package itself but to its integration with Firebase.

If there are many requests or volunteers, I will be happy to add the sample codes under the example project.

**Comment by fisforfaheem** [comment]
Great.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/18/22,
12:57:18 AM
