### ISSUE TITLE
Ability to change forgot password location

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#45]
Usually the forgot password is place under the login button.

There are multiple solution but here I propose a cool one....I think.

We would need to have a way to order components.

A suggestion:
Define an enum
enum Components{
title,
title_description,
form,
login_action_button,
accrount_creation_action,
forgot_password_action
}

Add a property **display_order** to the AnimatedLogin class **OR** to the Theme with a default value provided for the list.
This will not break the current API.

And you can mark the showForgotPassord as deprecated....and in the meantime when this is true...change the display_order list !
Same thing for showChangeActionTitle

LMM

**Comment by bahricanyesil** [comment]
Enabling custom order of components is a great idea, thanks @wer-mathurin ! I will be implementing ASAP. It seems to fit in my mind.
