### ISSUE TITLE
No space between title description and form

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#46]
Here is a screenshot when spacingWithoutSocial is set to 0

![image](https://user-images.githubusercontent.com/39314023/151988722-22ecbfed-e0cf-48c2-90ce-e89003b8bef2.png)

**Comment by mlakkapr** [comment]
@bahricanyesil Just submitted a PR with a fix to this issue.

**Comment by bahricanyesil** [comment]
Thanks for pointing out @wer-mathurin, sorry for late response.

Thank you @mlakkapr, I just reviewed. Can you check my review?

**Comment by bahricanyesil** [comment]
What did you expect as a result @wer-mathurin ? "spacingWithoutSocial" means the spacing between the form and titles if there is no social login. So, if you set it to 0, then there should not be any space and as I can see from your screenshot there is no space. What did you expect? I'm confused or missed something, can you explain your expectation?

Thanks.

**Comment by bahricanyesil** [comment]
No problem, thanks for your consideration.

So you think that even if the package user set it to 0, there should be some default spaces. Am I wrong? Then how can a person who really wants to put 0 spacing / put no spacing implement it?

You are right about the padding part, I will convert it into EdgeInsets property for more customizable system. What came into my mind:
1- If user doesn't set it, use the default value (whatever it is)
2-If user wants to set no space, s/he can use EdgeInsets.zero
3- S/he can set any value.

**Comment by wer-mathurin** [comment]
Maybe a default EdgeInsets.only(bottom: 16) can be a good starting point.
If you consider EdgetInsets.all(8), this will lead having 16 spacing between 2 components.

But if we specify EdgeInsets.zero...we must have zero spacing like the screenshot :-)
