### ISSUE TITLE
Validators

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#5]
There is no way to overpass the password validation other than passing false to the LoginTheme (showFormFieldErrors: false).
I think this is misleading.

The general use case:
As of user, I want to be able to use my own validator on fields and decide when to apply it.

**Comment by bahricanyesil** [comment]
You're certainly right! I will add optional validators for custom validation and bool parameters to decide whether to validate or not. Let me know if you need any additional parameters apart from these.

**Comment by wer-mathurin** [comment]
Not so far! I'm just starting playing with it :-)

**Comment by wer-mathurin** [comment]
@bahricanyesil : Maybe one thing, regroup theming stuff in the LoginTheme, an example would be => actionButtonStyle

**Comment by bahricanyesil** [comment]
> @bahricanyesil : Maybe one thing, regroup theming stuff in the LoginTheme, an example would be => actionButtonStyle

Do you mean for example under a "LoginButtonStyles" class?

**Comment by wer-mathurin** [comment]
Maybe move the property to the LoginTheme.
Because when when want to them the Login, we need to do it in the
AnimatedLogin class for certain things and LoginTheme for others

**Comment by bahricanyesil** [comment]
> Maybe move the property to the LoginTheme. Because when when want to theme the Login, we need to do it in the AnimatedLogin class for certain things and LoginTheme for others

Ah, yeah. I got your point now. Thank you for the suggestion, that makes more sense. I'm creating a new issue for that.
