### ISSUE TITLE
animatedComponentOrder missing export AnimationType

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#53]
When using the animatedComponentOrder since the AnimationType is not export with the library we can't use the FULL functionnality. (controlling the animation LEFT and RIGHT)

**Comment by bahricanyesil** [comment]
Sorry for the late response @wer-mathurin. I will be analyzing and dealing with this issue in couple of weeks.

**Comment by bahricanyesil** [comment]
It is solved by #60, it will be published in the next version (1.5.3).
