### ISSUE TITLE
add loginTexts.signupemailhint

### ISSUE THREAD

**Issue by tas-unn** [bahricanyesil/flutter-animated-login#68]
My authorization works both by corporate login and by email, but registration can only be by email (corporate login is issued elsewhere). Therefore, please share hints for email in authorization and registration
![image](https://user-images.githubusercontent.com/92320184/204229686-05d0bfef-914a-4134-bad6-801461e11e4c.png)

**Comment by bahricanyesil** [comment]
I couldn't understand your request @tas-unn, can you please give more details about what is the problem and what are you trying to achieve?

**Comment by tas-unn** [comment]
2 textboxes have one hint in logintexts (named emailhint) . I think it must be 2 too

**Comment by bahricanyesil** [comment]
I got it now, sorry for too late response due to the university and work-related stuff. I will add this as soon as possible this month with the next release.

**Comment by bahricanyesil** [comment]
Hi again @tas-unn, I implemented your request in the new version (1.6.0) and published it on pub.dev. Therefore, I'm closing the issue. Please re-open it if you need further support or request related to this issue.
