### ISSUE TITLE
Icon in password-input is too large

### ISSUE THREAD

**Issue by GyroGoober** [bahricanyesil/flutter-animated-login#69]
**Describe the bug**
Opening the app either in web or desktop, the hide/show-icon button in the password-inputs are too large. This also leads to the password-input having a greater height compared to the other inputs. All password inputs (in login and in registration) are affected.

**To Reproduce**
1. Open login or registration in windows/chrome
2. notice the too large hide/show icons in the password input

**Code Example**
```dart
  @override
  Widget build(BuildContext context) {
    return AnimatedLogin(
      onLogin: mounted ? LoginFunctions(context).onLogin : null,
      onSignup: mounted ? LoginFunctions(context).onSignup : null,
      onForgotPassword:
          mounted ? LoginFunctions(context).onForgotPassword : null,
      loginDesktopTheme: _desktopTheme,
      loginMobileTheme: _mobileTheme,
      loginTexts: _loginTexts,
      changeLanguageCallback: (LanguageOption? language) {
        if (language != null) {
          DialogBuilder(context).showResultDialog(
            'Successfully changed the language to: ${language.value}.',
          );
          if (mounted) setState(() => language = language);
        }
      },
      languageOptions: _languageOptions,
      selectedLanguage: language,
      initialMode: currentMode,
      onAuthModeChange: (AuthMode newMode) => currentMode = newMode,
    );
  }
```

**Expected behavior**
Icons should be similar in size to the mobile views. 

**Screenshots**
![Screenshot of View while logging in](https://user-images.githubusercontent.com/62655784/209117130-f7817d6e-02ca-4b17-8959-939b7b2c84a9.jpg)
![Screenshot of View while registering](https://user-images.githubusercontent.com/62655784/209122218-bc0811a7-39ff-40fe-8fc0-f6431e496e6c.jpg)

**Platforms, Devices, and Versions**
 - Platforms [Windows, Web]
 - Browser [chrome (not tested on others)]
 - Flutter Version [3.3.7]
 - Animated Login Package Version [v1.5.5]

**Comment by bahricanyesil** [comment]
Thank you for the very descriptive and detailed issue @GyroGoober! You explained the bug with a good description and screenshots. Thanks for the effort.

When I run on my local, the icon seems to have the expected size as follows:
<img width="1012" alt="Screen Shot 2023-01-08 at 00 50 01" src="https://user-images.githubusercontent.com/60237280/211171527-90503480-3be3-4a78-b2fe-63a172edfe84.png">

I'm wondering if you changed something. Do you encounter this problem every time you try to run the example project, am I wrong? Did you make any modifications or have a special condition for this problem?

**Comment by bahricanyesil** [comment]
I am closing the issue due to the inactivity and no answer from @GyroGoober

**Comment by GyroGoober** [comment]
Hello @bahricanyesil, I'm sorry for not responding earlier, the notification got buried and I didn't see you updating the issue. 

I have not made any changes to the icons, and they are indeed the correct size in the example. 
So either:
* I did make some changes (unknowingly)
or 
* something seemingly unrelated caused the icons to be in the wrong size

Regardless, some further debugging is needed on my part. If I find a condition triggering this bug, I will let you know, otherwise, it is safe to assume that your library is/was not at fault.

Also a big thanks for taking the time to create this awesome repo and sharing it!
