### ISSUE TITLE
PasswordVisibility icon is huge when the application ThemeData set the useMaterial3 to true

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#74]
**Describe the bug**
![image](https://github.com/bahricanyesil/flutter-animated-login/assets/39314023/37cc4430-441f-4c85-8f70-c7bdd1042ca4)

**Comment by bahricanyesil** [comment]
Thanks for reporting @wer-mathurin, I will solve it.

**Comment by bahricanyesil** [comment]
@wer-mathurin Can you share more details regarding this bug? Which platform did you encounter?

**Comment by wer-mathurin** [comment]
@bahricanyesil:
Flutetr 3.10.x and up

For the Web

**Comment by bahricanyesil** [comment]
@wer-mathurin Which browser?

**Comment by wer-mathurin** [comment]
> @wer-mathurin Which browser?

Chrome

**Comment by bahricanyesil** [comment]
@wer-mathurin Can there be some problems with your code or your custom parameters? I am running the example app and this is the result I got:

<img width="1510" alt="Screenshot 2023-08-18 at 00 12 44" src="https://github.com/bahricanyesil/flutter-animated-login/assets/60237280/aa3a8a93-2855-42a9-8389-e9b58ccb0e78">

**Comment by wer-mathurin** [comment]
@bahricanyesil:

it seems you are right...by removing our custom theme at the application level, this is not ok. 
This seems to be causes by the flag material3 from this library.  If you uncomment the // useMaterial3: true you will have a big eye :-)
 
```
final theme = FlexColorScheme.light(
      scheme: FlexScheme.bahamaBlue,
      surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
      blendLevel: 1,
      subThemesData: const FlexSubThemesData(
        useTextTheme: true,
        useM2StyleDividerInM3: true,
        defaultRadius: 12.0,
        elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
        elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
        outlinedButtonOutlineSchemeColor: SchemeColor.primary,
        toggleButtonsBorderSchemeColor: SchemeColor.primary,
        segmentedButtonSchemeColor: SchemeColor.primary,
        segmentedButtonBorderSchemeColor: SchemeColor.primary,
        unselectedToggleIsColored: true,
        sliderValueTinted: true,
        inputDecoratorSchemeColor: SchemeColor.primary,
        inputDecoratorBackgroundAlpha: 31,
        inputDecoratorRadius: 4.0,
        inputDecoratorUnfocusedBorderIsColored: false,
        inputDecoratorFocusedHasBorder: true,
        inputDecoratorFocusedBorderWidth: 1.0,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
        fabUseShape: true,
        fabAlwaysCircular: true,
        fabSchemeColor: SchemeColor.tertiary,
        popupMenuRadius: 8.0,
        popupMenuElevation: 3.0,
        drawerIndicatorRadius: 12.0,
        drawerIndicatorSchemeColor: SchemeColor.primary,
        bottomNavigationBarMutedUnselectedLabel: false,
        bottomNavigationBarMutedUnselectedIcon: false,
        menuRadius: 8.0,
        menuElevation: 3.0,
        menuBarRadius: 0.0,
        menuBarElevation: 2.0,
        menuBarShadowColor: Color(0x00000000),
        navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
        navigationBarMutedUnselectedLabel: false,
        navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationBarMutedUnselectedIcon: false,
        navigationBarIndicatorSchemeColor: SchemeColor.primary,
        navigationBarIndicatorOpacity: 1.00,
        navigationBarIndicatorRadius: 12.0,
        navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
        navigationRailMutedUnselectedLabel: false,
        navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationRailMutedUnselectedIcon: false,
        navigationRailIndicatorSchemeColor: SchemeColor.primary,
        navigationRailIndicatorOpacity: 1.00,
        navigationRailIndicatorRadius: 12.0,
        navigationRailBackgroundSchemeColor: SchemeColor.surface,
      ),
      keyColors: const FlexKeyColors(
        useSecondary: true,
        useTertiary: true,
        keepPrimary: true,
      ),
      tones: FlexTones.jolly(Brightness.light),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      // useMaterial3: true,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ).toTheme;
```

**Comment by bahricanyesil** [comment]
@wer-mathurin actually the problem was not related to your code. I realized that I am mistakenly passing size value for the size factor parameter of base icon. I will now fix it.

**Comment by bahricanyesil** [comment]
@wer-mathurin can you check the latest version of he package?

**Comment by wer-mathurin** [comment]
If you add this to the app theme you will have the big icon.
This mean in the next stable verion of Flutter (after 3.13)  this will happen:

**FROM THE ANNNOUNCEMENT**
We’re excited to announce that in the next Flutter stable release we plan to change the ThemeData useMaterial3 default from false to true. In other words, applications will get the Material 3 colors, text styles, and other visuals, by default.
 
Add this this to the app to reproduce
 theme: ThemeData(useMaterial3: true),

**Comment by bahricanyesil** [comment]
@wer-mathurin I did it and realized the real problem, please refer to this:

> @wer-mathurin actually the problem was not related to your code. I realized that I am mistakenly passing size value for the size factor parameter of base icon. I will now fix it.

I will do the material3 migration in a separate version update.

**Comment by bahricanyesil** [comment]
@wer-mathurin You can also state the points needed to be updated with material3.

**Comment by bahricanyesil** [comment]
I did not detect a big problem except the primary color of the example app, and that's just related to the example app. Do you have anything you think it needed to be updated with material 3 update?

**Comment by bahricanyesil** [comment]
@wer-mathurin please refer to #76 for material 3 migration.
