### ISSUE TITLE
Material 3 Migration

### ISSUE THREAD

**Issue by bahricanyesil** [bahricanyesil/flutter-animated-login#76]
With the latest update of Flutter, material 3 will be the default. You can reach out for the details [here](https://medium.com/flutter/whats-new-in-flutter-3-13-479d9b11df4d).

Therefore, we need to update some text styles, colors, decorations, etc.

**Comment by bahricanyesil** [comment]
@wer-mathurin please test your app with v1.7.2 of this package and report to me any issue you encounter including the eye size for hiding the password.

**Comment by wer-mathurin** [comment]
@bahricanyesil: Working for me.

Good job :-)

**Comment by bahricanyesil** [comment]
> @bahricanyesil: Working for me.
> 
> 
> 
> Good job :-)

Thank you ☺️
